import type { Metadata } from "next";
import { Geist } from "next/font/google";
import Script from "next/script";
import { AgeGate } from "@/components/AgeGate";
import { AnnouncementBar } from "@/components/AnnouncementBar";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";
import { MobileStickyCta } from "@/components/MobileStickyCta";
import { CartResumeBanner } from "@/components/CartResumeBanner";
import { ServiceWorkerRegister } from "@/components/ServiceWorkerRegister";
import { InstallAppBanner } from "@/components/InstallAppBanner";
import { STORE } from "@/lib/store";
import "./globals.css";
import { safeJsonLd } from "@/lib/json-ld-safe";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });

// GA4 measurement ID — when Doug enables GA4 in the dashboard, paste the
// "G-XXXXXXX" measurement ID into NEXT_PUBLIC_GA_ID on Vercel and the
// gtag.js loader auto-renders site-wide. Empty = no-op (zero bytes shipped).
const GA_ID = process.env.NEXT_PUBLIC_GA_ID ?? "";

export const metadata: Metadata = {
  metadataBase: new URL(STORE.website),
  title: {
    // Brand-anchor title: name → category → city → founded year. Google
    // weights the first ~60 chars; everything before "WA" is the part
    // that earns the SERP click.
    default: `${STORE.name} | Cannabis Dispensary in ${STORE.address.city}, WA — Founded 2014`,
    template: `%s | ${STORE.name}`,
  },
  // 156 chars (within Google's 160 SERP cap). Compresses the long form
  // to brand + city + founded year + categories + cash-only signal.
  // Sister of GW v2.92 meta-description length sweep + scc trim. v10.105.
  description: `${STORE.name} — ${STORE.address.city} cannabis dispensary since 2014. Flower, edibles, concentrates, vapes, pre-rolls, tinctures, topicals. Cash only, 21+.`,
  keywords: [
    "cannabis dispensary Wenatchee",
    "marijuana dispensary Wenatchee WA",
    "cannabis store Wenatchee",
    "weed dispensary Wenatchee",
    "Green Life Cannabis",
    "cannabis delivery Wenatchee",
    "recreational cannabis Washington",
  ],
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: STORE.website,
    siteName: STORE.name,
    title: `${STORE.name} | Cannabis Dispensary in ${STORE.address.city}, WA — Founded 2014`,
    description: `Shop premium cannabis at ${STORE.name} — 12+ yrs · Wenatchee's most-known team, founded 2014. Flower, edibles, concentrates, vapes & more.`,
    images: [
      {
        // Auto-generated by app/opengraph-image.tsx — Next emits the route
        // at /opengraph-image and the convention auto-wires it. Listing
        // explicitly here makes the alt + dimensions visible to crawlers
        // that don't follow the metadata convention (older Slack/iMessage
        // unfurlers).
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: `${STORE.name} — Cannabis Dispensary in Wenatchee, WA`,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    // `title`, `description`, AND `images` all intentionally NOT set
    // here — when omitted, Twitter's crawler falls back to og:title +
    // og:description + og:image (per Twitter Cards spec + Next 16
    // metadata cascade).
    //
    // - title: pre-fix layout hard-coded `${STORE.name} | ...` and child
    //   pages overrode openGraph.title but never twitter.title — every
    //   brand / blog / about / near / heroes share card on Twitter/X
    //   showed the layout default. Caught 2026-05-10 by /loop tick 7.
    //
    // - images: pre-fix layout hard-coded ["/opengraph-image"] (the
    //   homepage OG) and child pages override openGraph.images via the
    //   per-route `opengraph-image.tsx` convention but never twitter.
    //   So /menu and /brands/[slug] share cards on Twitter/X showed the
    //   homepage OG image instead of the per-route custom one. Caught
    //   2026-05-10 by /loop tick 9 cross-stack og:image vs twitter:image
    //   comparison (2/9 sample pages mismatched). Sister scc same-class.
  },
  robots: {
    index: true,
    follow: true,
    // Modern Google SERP-display directives. Without these, Google uses
    // conservative defaults: shorter snippets (~160c), smaller image
    // previews, no video preview. With them, Google can show full-
    // length snippets, large image previews (better for visual SERP
    // layout — important for cannabis/dispensary search where customers
    // scan for brand recognition), and full video previews. Pure
    // additive SERP-visibility win. Sister scc + GW same-fix. Caught
    // 2026-05-10 by /loop tick 65 robots-meta detail audit.
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
      "max-video-preview": -1,
    },
  },
  // Search Console + Bing Webmaster Tools + Yandex verification —
  // env-gated. When Doug enables verification in any dashboard, paste
  // the token into the matching env var on Vercel and the meta tag
  // renders site-wide. Empty env = empty meta = no-op (Next renders
  // nothing for an undefined value). Cleaner than HTML-file verification
  // since these tags survive route-level metadata overrides on inner
  // pages. v… 2026-05-09 SEO arc — sister of GW + SCC + CannAgent.
  verification: {
    google: process.env.GOOGLE_SITE_VERIFICATION || undefined,
    other: {
      ...(process.env.BING_SITE_VERIFICATION
        ? { "msvalidate.01": process.env.BING_SITE_VERIFICATION }
        : {}),
      ...(process.env.YANDEX_VERIFICATION
        ? { "yandex-verification": process.env.YANDEX_VERIFICATION }
        : {}),
    },
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "Green Life",
  },
  // applicationName — emits `<meta name="application-name">`. Used by
  // Microsoft Edge + Windows Start menu when pinning the site as a
  // tile / app shortcut, and by some browser plugins as the canonical
  // app identifier. Pre-fix all 3 sites in the stack were missing this
  // (curl audit). Pure additive — no existing functionality affected.
  // Sister scc + GW same-fix. Caught 2026-05-10 by /loop tick 56
  // cross-stack application-name audit.
  applicationName: "Green Life Cannabis",
  // iOS auto-formats numeric strings as tap-callable / tap-mail / tap-date
  // by default — body text containing zip codes (98801), WSLCB license
  // numbers (414755), prices ($25), dates (5/15), addresses, etc gets
  // auto-styled as tap targets that on click open the dialer / Maps /
  // Calendar. Customer trying to highlight an address may accidentally
  // open Maps; tapping a 5-digit number expecting it to be a zip may
  // dial it as a phone extension. Disable auto-detection sitewide; we
  // already use explicit `<a href="tel:…">` for the actual phone number
  // (verified — STORE.phoneTel surfaced in 3+ tel-href hits per page).
  // Sister scc + GW same-fix v15.X / v13.X / v2.96.50. Caught
  // 2026-05-10 by /loop tick 42 cross-stack format-detection audit.
  formatDetection: {
    telephone: false,
    date: false,
    address: false,
    email: false,
  },
  // Explicit apple-touch-icon link — Next 16 doesn't auto-emit `<link
  // rel="apple-touch-icon">` for route-handler-based icons (we use
  // `app/apple-icon.png/route.tsx` for dynamic ImageResponse generation,
  // not a static binary). Without this, iOS Safari "Add to Home Screen"
  // falls back to a generic globe icon. The route already serves 200 +
  // 180×180 PNG; this just points iOS at it.
  icons: {
    apple: { url: "/apple-icon.png", sizes: "180x180", type: "image/png" },
  },
  other: {
    rating: "adult",
    // `mobile-web-app-capable` REMOVED — `appleWebApp.capable: true` above
    // already emits the modern `<meta name="mobile-web-app-capable">` (Next 16
    // upgraded the legacy `apple-mobile-web-app-capable` to the platform-
    // neutral form). Pre-fix BOTH metadata sources fired so the rendered HTML
    // contained the meta TWICE on every page — Lighthouse PWA + W3C validator
    // both flag duplicate-meta. Caught 2026-05-10 by /loop cross-stack
    // mobile-web-app meta presence sweep. Sister scc same-push.
    // Geo SEO meta — paid display + CRM ad networks (Meta/Google Ads/
    // Klaviyo) anchor location-targeted creative off these. ICBM +
    // geo.position duplicate each other on purpose; different crawlers
    // prefer different conventions.
    "geo.region": "US-WA",
    "geo.placename": `${STORE.address.city}, WA`,
    "geo.position": `${STORE.geo.lat};${STORE.geo.lng}`,
    ICBM: `${STORE.geo.lat}, ${STORE.geo.lng}`,
  },
};

export const viewport = {
  themeColor: "#022c22",
  // colorScheme: "light" — emits `<meta name="color-scheme" content="light">`.
  // Pre-fix the meta was absent, so browsers' auto-dark-mode logic could
  // re-tint form inputs, scrollbars, and default UA UI to dark on systems
  // where the user prefers dark mode. This site is light-themed by design
  // (cream/stone-50 backgrounds, dark text); auto-dark-tinting clashes
  // with Tailwind explicit color classes (e.g. an input bg-white style
  // gets coerced toward dark gray by Chrome's auto-dark engine, breaking
  // contrast). Declaring the supported scheme explicitly opts out of the
  // auto-adjust. Sister scc + GW same-fix. Caught 2026-05-10 by /loop
  // tick 43 cross-stack color-scheme audit.
  colorScheme: "light",
  width: "device-width",
  initialScale: 1,
};

// Headline towns in the Wenatchee Valley footprint live in `STORE.nearbyTowns`
// so the homepage hero pill cluster + town card grid pull from the same
// source as the JSON-LD areaServed graph below. The longer list here adds
// the smaller communities + neighborhoods we also serve so search engines
// see the full geographic reach without the homepage rendering a marketing
// wall of pills.
const NEARBY_CITIES = [
  ...STORE.nearbyTowns.map((t) => t.name),
  "Quincy",
  "Waterville",
  "Malaga",
  "Monitor",
  "Sunnyslope",
];

// Convert STORE.hours format ("8:00 AM" / "9:00 PM") → schema.org ISO 24h
// ("08:00" / "21:00"). schema.org/openingHoursSpecification REQUIRES the
// 24h ISO format; the AM/PM strings we feed the UI fail validation in
// Google Rich Results Test. Local helper to avoid touching lib/store.ts.
function toIso24(t: string): string {
  const [time, ampm] = t.split(" ");
  const [hStr, mStr] = time.split(":");
  let h = Number(hStr);
  if (ampm === "PM" && h !== 12) h += 12;
  if (ampm === "AM" && h === 12) h = 0;
  return `${String(h).padStart(2, "0")}:${mStr.padStart(2, "0")}`;
}

// Canonical Organization @id reused across schemas so Google graphs the
// LocalBusiness, WebSite, and Organization as one entity instead of three
// disconnected nodes. The "#" anchor convention is what the schema.org
// extension docs recommend.
const ORG_ID = `${STORE.website}/#organization`;
const WEBSITE_ID = `${STORE.website}/#website`;
const LOGO_URL = `${STORE.website}/icon-512.png`;

const sameAsLinks = [
  STORE.social.instagram,
  STORE.social.facebook,
  STORE.googleMapsUrl,
].filter(Boolean);

// Organization — anchors brand identity. mainEntityOfPage points at the
// homepage so a "Green Life" brand search lifts / not /menu. Ties together
// LocalBusiness + WebSite via the shared @id graph above.
const organizationSchema = {
  "@context": "https://schema.org",
  "@type": "Organization",
  "@id": ORG_ID,
  name: STORE.name,
  legalName: "Verve Mgmt LLC",
  alternateName: ["Green Life", "Green Life Cannabis", "Green Life Wenatchee"],
  url: STORE.website,
  logo: {
    "@type": "ImageObject",
    url: LOGO_URL,
    width: 512,
    height: 512,
  },
  image: `${STORE.website}/opengraph-image`,
  description: `${STORE.address.city}'s cannabis dispensary, founded 2014. Same building in Sunnyslope. Best cannabis staff in the Valley.`,
  foundingDate: "2014",
  foundingLocation: {
    "@type": "Place",
    name: `${STORE.address.city}, WA`,
  },
  areaServed: {
    "@type": "State",
    name: "Washington",
  },
  contactPoint: {
    "@type": "ContactPoint",
    telephone: STORE.phoneTel,
    contactType: "customer service",
    areaServed: "US-WA",
    availableLanguage: ["English", "Spanish"],
  },
  mainEntityOfPage: {
    "@type": "WebPage",
    "@id": `${STORE.website}/`,
  },
  sameAs: sameAsLinks,
};

// WebSite + SearchAction — enables Google's sitelinks search box. The
// {search_term_string} placeholder is part of the schema spec, not a
// Next route param. Lands on /menu (live inventory) since that is what
// customers want to search for. Critical for "Green Life menu blue dream"
// or similar long-tail brand-search-with-product queries.
const websiteSchema = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  "@id": WEBSITE_ID,
  url: STORE.website,
  name: STORE.name,
  alternateName: "Green Life Cannabis",
  description: `${STORE.name} — ${STORE.address.city}'s cannabis dispensary since 2014.`,
  publisher: { "@id": ORG_ID },
  inLanguage: "en-US",
  // No `potentialAction: SearchAction` — see v15.705 revert note below.
  //
  // T33 (v15.305) shipped a SearchAction pointing at `/order?q=...` because
  // OrderMenu.tsx reads `?q=` searchParams. T36 (v15.705) reverted that:
  // `/order` 307-redirects to `/menu` per `proxy.ts` (verified via curl
  // post-T33 — same behavior memorialized in v7.785's pre-fix history). And
  // /menu (iHJ Boost embed) doesn't consume `?q=` either. Neither URL is a
  // working query-aware target, so we drop the SearchAction entirely (same
  // reasoning as GW v2.95.60 had no working endpoint). Re-add when /menu
  // wires up `?q=` passthrough to Boost. Doug operating-principle: customer
  // CTAs on glw + scc point to `/menu` only — never `/order` direct (extra
  // redirect hop wastes crawl-citation + violates SoT).
};

const localBusinessSchema = {
  "@context": "https://schema.org",
  "@type": ["LocalBusiness", "Store"],
  "@id": `${STORE.website}/#dispensary`,
  name: STORE.name,
  legalName: "Verve Mgmt LLC",
  alternateName: ["Green Life", "Green Life Wenatchee"],
  description: `Licensed cannabis dispensary in ${STORE.address.city}, WA — founded 2014, same building in Sunnyslope, the Valley's best cannabis staff. Premium flower, pre-rolls, vapes, concentrates, edibles, tinctures and topicals from Washington-state producers. Cash only, 21+ with valid ID.`,
  slogan: STORE.tagline,
  url: STORE.website,
  image: `${STORE.website}/opengraph-image`,
  logo: LOGO_URL,
  telephone: STORE.phoneTel,
  email: STORE.email,
  foundingDate: "2014",
  parentOrganization: { "@id": ORG_ID },
  address: {
    "@type": "PostalAddress",
    streetAddress: STORE.address.street,
    addressLocality: STORE.address.city,
    addressRegion: STORE.address.state,
    postalCode: STORE.address.zip,
    addressCountry: "US",
  },
  geo: {
    "@type": "GeoCoordinates",
    latitude: STORE.geo.lat,
    longitude: STORE.geo.lng,
  },
  areaServed: [
    // City-level served-area entries — what we already had, drives "{city}
    // dispensary" intent.
    ...NEARBY_CITIES.map((name) => ({
      "@type": "City",
      name,
      containedInPlace: { "@type": "State", name: "Washington" },
    })),
    // ZIP-code-level served-area entries (Hack #8 — Local SEO).
    // Drives "cannabis 98801" / "weed near 98826" intent — zip-code
    // queries are 2-3× higher purchase intent than city queries because
    // they typically come from people checking what's actually near them
    // RIGHT NOW. Schema.org PostalCodeSpecification under areaServed is
    // the canonical way to advertise the radius without lying about
    // delivery (we're pickup-only — these are the ZIPs we DRAW from,
    // not where we ship to). Snohomish-county-cities and Quincy excluded
    // since those are 2hr+ drives. Wenatchee Valley + immediate I-90
    // / US-2 corridor only.
    ...[
      { zip: "98801", area: "Wenatchee + Sunnyslope" },
      { zip: "98802", area: "East Wenatchee" },
      { zip: "98815", area: "Cashmere" },
      { zip: "98826", area: "Leavenworth" },
      { zip: "98816", area: "Chelan + Lake Chelan" },
      { zip: "98822", area: "Entiat" },
      { zip: "98823", area: "Quincy + Ephrata corridor" },
      { zip: "98847", area: "Peshastin" },
    ].map(({ zip, area }) => ({
      "@type": "PostalAddress",
      postalCode: zip,
      addressRegion: "WA",
      addressCountry: "US",
      description: area,
    })),
  ],
  openingHoursSpecification: STORE.hours.map((h) => ({
    "@type": "OpeningHoursSpecification",
    dayOfWeek: `https://schema.org/${h.day}`,
    // Schema.org expects ISO 24h ("08:00") not the AM/PM strings the UI
    // uses. Was emitting "8:00 AM" which Rich Results Test flags as
    // invalid and Google ignores.
    opens: toIso24(h.open),
    closes: toIso24(h.close),
  })),
  priceRange: "$",
  currenciesAccepted: "USD",
  paymentAccepted: ["Cash"],
  hasMap: STORE.googleMapsUrl,
  identifier: {
    "@type": "PropertyValue",
    propertyID: "WSLCB License",
    value: STORE.wslcbLicense,
  },
  knowsAbout: [
    "Cannabis flower",
    "Pre-rolls",
    "Cannabis concentrates",
    "Cannabis vapes",
    "Cannabis edibles",
    "Tinctures",
    "Topicals",
    "Terpenes",
    "Cannabinoids",
    "Indica",
    "Sativa",
    "Hybrid",
    "Washington State cannabis law",
  ],
  amenityFeature: STORE.amenities.map((name) => ({
    "@type": "LocationFeatureSpecification",
    name,
    value: true,
  })),
  publicAccess: true,
  smokingAllowed: false,
  isAccessibleForFree: true,
  hasMenu: `${STORE.website}/menu`,
  potentialAction: {
    "@type": "OrderAction",
    target: `${STORE.website}/menu`,
    deliveryMethod: "http://purl.org/goodrelations/v1#DeliveryModePickUp",
  },
  // Speakable spec — tells voice assistants (Siri / Google Assistant /
  // Alexa / Apple Intelligence) which DOM nodes to read aloud when a
  // user asks "what are the hours of Green Life Cannabis" via a
  // voice-only surface. Pairs with `className="speakable-*"` tags on
  // the SiteFooter address + hours + phone elements so the schema and
  // the prose stay coupled.
  speakable: {
    "@type": "SpeakableSpecification",
    cssSelector: [".speakable-address", ".speakable-hours", ".speakable-phone"],
  },
  sameAs: sameAsLinks,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // ClerkProvider deliberately NOT here — it preloads `clerk.accounts.dev`
  // (or the satellite Clerk URL) on every page including /menu, which
  // injects scripts and cookies that interfere with the iHeartJane Boost
  // embed's cross-origin XHR. Provider is now scoped to /account, /sign-in,
  // /sign-up via per-route layout.tsx files. SiteHeader's previous
  // `useAuth()` was removed (always shows "Sign in" link — Clerk redirects
  // signed-in visitors to /account on the /sign-in page). Server-side
  // helpers from `@clerk/nextjs/server` (auth, currentUser) work without
  // ClerkProvider so /account pages still authenticate correctly.
  return (
    <html lang="en" className={`${geistSans.variable} h-full`}>
      <head>
        {/* Resource hints — DNS + TLS prewarm for vendor-image CDNs we hit
            on home, /brands, /menu, /order. Browsers open the TCP + TLS
            connection in parallel with HTML parse instead of sequentially
            after first reference. Real Core Web Vitals win on mobile
            (~100–200ms per origin on cold connections). Clerk hosts NOT
            preconnected here — ClerkProvider is scoped to /sign-in,
            /sign-up, /account via per-route layouts (see comment below).
            crossOrigin="anonymous" because images are fetched without
            credentials; required for the connection to be reused. */}
        <link rel="preconnect" href="https://images.squarespace-cdn.com" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://static.wixstatic.com" crossOrigin="anonymous" />
        {/* Three coordinated JSON-LD payloads. Together they tell Google
            (a) what the brand is (Organization), (b) that the SITE has
            a search box that should appear under the homepage in SERPs
            (WebSite + SearchAction — sitelinks searchbox), and (c) the
            full physical-place NAP+hours+geo (LocalBusiness/Store). The
            shared @id graph (ORG_ID, WEBSITE_ID, #dispensary) lets the
            knowledge graph stitch them. Adding the Organization +
            WebSite schemas makes / outrank /menu in brand searches —
            without them, Google has no signal that / is the canonical
            entity hub.  */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: safeJsonLd(organizationSchema) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: safeJsonLd(websiteSchema) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: safeJsonLd(localBusinessSchema) }}
        />
      </head>
      <body className="min-h-full flex flex-col bg-stone-50 text-stone-900">
        {/* Skip-to-main — keyboard + screen-reader users tab here first
            so they can bypass the header/announcement nav. Visually hidden
            until focused, then becomes a fixed pill at the top-left. */}
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:top-3 focus:left-3 focus:z-[100] focus:px-4 focus:py-2 focus:rounded-xl focus:bg-green-700 focus:text-white focus:font-bold focus:text-sm focus:shadow-2xl focus:outline-none focus:ring-2 focus:ring-green-400 focus:ring-offset-2"
        >
          Skip to main content
        </a>
        <AgeGate />
        <AnnouncementBar />
        <SiteHeader />
        <CartResumeBanner />
        <main id="main" className="flex-1">
          {children}
        </main>
        <SiteFooter />
        <MobileStickyCta />
        <ServiceWorkerRegister />
        <InstallAppBanner />
        {/* GA4 — auto-loads when Doug pastes a "G-XXXXXXX" measurement
            ID into NEXT_PUBLIC_GA_ID on Vercel. Empty env = nothing
            renders; zero bytes shipped. afterInteractive so it doesn't
            block hydration. Sister pattern to GW root layout. */}
        {GA_ID && (
          <>
            <Script
              src={`https://www.googletagmanager.com/gtag/js?id=${GA_ID}`}
              strategy="afterInteractive"
            />
            <Script id="gtag-init" strategy="afterInteractive">
              {`window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','${GA_ID}',{page_path:window.location.pathname});`}
            </Script>
          </>
        )}
      </body>
    </html>
  );
}
