// Build identity exposed in the footer so Doug can verify a deploy landed.
// Bump BUILD_VERSION manually for major UX/feature changes; the short SHA
// comes from Vercel automatically on every deploy and is the authoritative
// "did my push actually land" signal.

// 3.260 — Homepage 🆕 Just In section. New `getJustInProducts(12)` lib fn pulls products with `inventory_snapshots.first_seen ≤ 7 days ago`, in stock now, with image, brand-with-recent-sales gate (same anti-leak as getMenuProducts). Renders above the (still-disabled-pending-/order-ship) Today's Picks block as a fresh 4-column grid with a "🆕 New" pill in the corner of each card. CTA links to /menu (iHeartJane Boost) — distinct from the in-dev /order tree. Distinct from curated /admin/marketing/featured (curated = hot picks, this = what's new). Doug 2026-05-04 "featured new products" — curated answers "featured", this answers "new". Mirror on seattle-cannabis-web v4.170.
// 3.255 — `getFeaturedProducts()` reads curated mode first. When admin (Kat/Doug) flips ON `is_featured` for any active product at inventoryapp /admin/marketing/featured (migration 0154), those products win the homepage carousel — sorted by `featured_priority DESC NULLS LAST, name ASC`. Falls back to the existing recent-`updated_at`-on-brands-with-sales auto-mode when zero curated. Companion to inventoryapp v44.x ship that landed migration 0154 + the admin curation surface. Mirror on seattle-cannabis-web v4.165.
// 3.250 — Homepage closure-aware. Adds `fetchClosureStatus()` to the page-level `Promise.all` and threads `closure.isClosed` into the existing `const open = isOpenNow()` so all 3 hero/strip/pre-footer "Open Now / Closed" indicators flip to "Closed" when a manager has flipped the emergency-closure override — matching the reality of the store, not just configured weekly hours. Also renders `<ClosureBanner>` at the very top of the page (above the hero) inside an amber strip for explicit reason context. Closure-aware customer surfaces now: `/` (v3.250) + `/menu` (v3.240) + `/order` (v3.230) + `/visit` (v3.245). Mirror on seattle-cannabis-web v4.160.
// 3.245 — `/visit` closure banner. Extends v3.240 to the third high-traffic customer entry point: the visit-info page (hours + directions + parking) where pre-drive customers land. Server Component made async to call `fetchClosureStatus()` server-side; banner renders above the hero when closed (consistent with /menu placement). Page already has `revalidate = 300` 5-min ISR so the closure-status fetch happens at most once per 5min per region. Closure-aware customer surfaces now: /menu (v3.240) + /order (v3.230) + /visit (v3.245). Mirror on seattle-cannabis-web v4.155.
// 3.240 — `/menu` server-rendered closure banner. Extends v3.230's `/order` banner to the higher-traffic `/menu` (iHeartJane Boost embed) entry point. New `<ClosureBanner>` component (presentational, used by both `/menu` server-side + `/order` client-side via prop). `/menu` page.tsx now does `Promise.all([getActiveDeals, fetchClosureStatus])` server-side; banner renders above the heading + JaneMenu when closed. ISR 60s on the page bounds the fetch frequency. Same graceful-degrade behavior — endpoint unreachable = banner doesn't render. Mirror on seattle-cannabis-web v4.150.
// 3.235 — `/brands` index deletion code lands (v3.225 changelog described this; that entry shipped via the closure-banner agent's bundle but the code edits were still uncommitted in working tree). This commit lands the actual file deletions + nav-strip + breadcrumb edits.
// 3.230 — `/order` block-on-closure banner. Fetches inventoryapp `/api/public/closure-status` on mount + before-submit re-check inside `placeOrder()`. When manager has flagged today closed via `/admin/hours-override`, surfaces an amber banner with the reason text, disables the Place Order button (label flips to "Closed today"), and the before-submit guard prevents a stale-state race. New `lib/closure-status.ts` helper wraps the fetch with a 5s AbortController timeout + always returns `{isClosed:false}` on any error path so a flaky endpoint never silently blocks ordering during normal hours. Default endpoint base = `inventoryapp-ivory.vercel.app`, overridable via `NEXT_PUBLIC_INVENTORYAPP_URL` (https-only). Closes the visibility chain queued in claude-loop-grinder Batch A items 1+2 (admin override v9.395 → public endpoint v9.745 → public-site banner now). Mirror on seattle-cannabis-web v4.140.
// 3.225 — `/brands` index page deleted (Doug + Kat call 2026-05-04). Even after the v3.181/v3.187/v3.205/v3.211 filter chain locked the data down to "products we currently carry + sold within 365 days," Kat's reasons for deletion were structural, not data-quality: (a) the page exposed our full vendor relationship list to outsiders; (b) it made daily-deal vendor concentration glanceable. Boutique `/brands/[slug]` overrides KEPT — they pull SEO traffic for "Phat Panda Wenatchee" / "Avitas WA" etc. queries and pay for themselves on direct link-sharing + deal-card click-throughs. **Touched:** index → 308 redirect to `/menu` (preserves any inbound link equity); SiteHeader nav, SiteFooter, home `Top Brands` section header (kept the section but stripped the "All N brands" + "+more" + empty-state links to the deleted index), about + visit page mesh tiles, not-found suggestion list, sitemap, llms.txt + llms-full.txt, vendor-access thanks page, blog post body. **`/brands/[slug]` template:** dropped "← All Brands" footer backlink + dropped "All Brands /" top-of-hero breadcrumb + dropped the "Brands" rung from the BreadcrumbList JSON-LD (now Home → {brand}). Per-brand override components (NWCS, Mfused, Avitas, Phat Panda, Plaid Jacket, etc.) intentionally NOT touched — those are graduated hand-authored layouts. Mirror on seattle-cannabis-web v4.135.
// 3.211 — Brand-leakage round 3 — sales-history gate extended to product surfaces (/order, /shop, /stash, home featured carousel, home category previews, brand-products grid). Round 2 (v3.205) only gated brand pages; products from leaked brands could still appear on /menu+/order+/shop because those don't go through getActiveBrands/getBrandBySlug. Now `getMenuProducts` + `getProductsByIds` + `getFeaturedProducts` (+ fallback) + `getCategoryPreviewProducts` + `getBrandProducts` all INNER JOIN `brands_with_recent_sales` (vendors with ≥1 sale_line_items.sold_at >= NOW() - INTERVAL '365 days'). Customer-facing product display surfaces are now uniformly gated. Mirror on seattle-cannabis-web v4.125.
// 3.205 — Brand-leakage round 2 — sales-history gate added to brand queries (Doug screenshot 2026-05-04: "ABS Buds" Wenatchee-era brand showing on Seattle with 13 FOG concentrate SKUs). Root cause: Seattle Neon has leaked inventory_snapshots from a seed migration; v4.107 qty>0 guard couldn't distinguish "real Seattle inventory" from "ghost inventory from a Wenatchee-seeded product." `getActiveBrands` + `getBrandBySlug` now INNER JOIN a `brands_with_recent_sales` CTE — each Neon DB only has THAT store's sales (per CLAUDE.md), so a `sale_line_items.sold_at >= NOW() - INTERVAL '365 days'` row = customer paid for it at this register. Brands without any tail sale at this store get hidden from /brands index AND 404 on direct `/brands/[slug]` visits (so the hand-authored override components for Wenatchee-only brands don't render either). Same fix on seattle-cannabis-web v4.119.
// 3.199 — `proxy.ts` /api/health exemption broadened from exact-equality to `startsWith("/api/health")` so the cheap second-bucket /api/health/ping liveness endpoint also stays reachable on apex / per-deployment Vercel URLs. Pre-fix: v3.193 fixed /api/health on apex but /api/health/ping was still 308'ing (uptime monitors that hit /ping every 30-60s for second-bucket liveness can't follow that redirect cleanly). Same fix applied to seattle-cannabis-web — covers both endpoints across both stores.
// 3.193 — `proxy.ts` /api/health exemption from the canonical-host 308 (parity with seattle-cannabis-web). Pre-fix: hitting `https://greenlifecannabis.com/api/health` (apex) or any per-deployment Vercel URL returned 308 → www, masking host-specific liveness signal — external uptime monitors, post-deploy LKG verification curls, and per-PR-deploy smoke-tests all got redirected away from the host they were probing. Now `if (!isCanonicalOrLocal && pathname !== "/api/health")` mirrors Seattle's behavior. Single line + comment update. No customer impact (customers don't hit /api/health). Curl from apex now returns 200 directly.
// 3.187 — Brand pages + featured + category previews now require current inventory (Doug bug report 2026-05-04 "showing items we hant had in a long time on both stores"). Layers on top of v3.181/v3.182 carry_status tightening: those went from `!=discontinued` to `=active` but didn't add a stock-level guard. Now `getActiveBrands` + `getBrandBySlug` + `getBrandProducts` + `getFeaturedProducts` (+ its 4-row fallback) + `getCategoryPreviewProducts` all join the canonical `latest_inv` CTE (`SELECT DISTINCT ON (product_id) ... ORDER BY product_id, captured_at DESC`) and filter `li.qty > 0`. Same pattern already in `getMenuProducts` + `getProductsByIds`. Customer no longer sees brands that haven't shipped a SKU in months, or "featured" products with empty shelves. WSLCB advertising-accuracy + customer-trust fix. Mirror on seattle-cannabis-web v4.107.
// 3.182 — `/order` + `/shop` + `/stash` product filter tightened (Doug bug report 2026-05-04 "saying we have things that we dont"). `getMenuProducts` + `getProductsByIds` in `lib/db.ts` now require strict `carry_status = 'active'` (was `!= 'discontinued'`, which included `phasing_out`) AND INNER JOIN to a latest-snapshot `qty > 0` CTE (was no current-stock filter at all — only the historical 7-day `is_new` subquery had any qty filter). Pairs with v3.181 brand-page tightening: same root cause (loose filter set), different consuming surfaces. Mirrors the inventoryapp `lib/menu-server.ts` canonical pattern. WSLCB advertising-accuracy + customer-trust fix. Mirror on seattle-cannabis-web v4.102.
// 3.181 — `/brands/[slug]` + `/brands` tightened product filter (Kat bug report 2026-05-04). `getActiveBrands` + `getBrandBySlug` + `getBrandProducts` in `lib/db.ts` now require `carry_status = 'active' AND unit_price > 0` instead of the looser `carry_status != 'discontinued'`. Hides phasing-out vendors, $0-priced placeholder rows, and Wenatchee-era stale products that customers were finding on brand pages we don't actually carry (Bon Bombs since-Wes era surfaced this). Same change shipped to seattle-cannabis-web v4.101 — Seattle had it worse since their DB inherited Wenatchee-era seed brands. SQL stays one query each, no N+1 introduced.
// 3.176 — Apply form `?position=` deep-link support — when /careers links to /apply?position={id}, form fetches position from inventoryapp API, pre-selects role + shows 'Applying for: {title}' pill at top. Hidden positionId field passes the link to /api/applications. Silent fallback when fetch fails or position no longer open.
// 3.171 — Public /careers landing (Hiring Phase 5). Fetches open positions from inventoryapp /api/positions/open?store=wenatchee with 5-min ISR + 5s fetch timeout (falls back to "we keep good resumes on file" empty state on any failure). Position cards: title, store badges (handles either→both), pay-range/hours-pattern chips, safe-markdown description (paragraphs + bullets + **bold** only — no HTML pass-through, XSS-safe), "Apply for this role" CTA deep-linking /apply?position={id}. Hero leans on Wenatchee's "best staff" angle (no "locally-owned" framing per project_wenatchee_positioning_best_staff). Mirror on seattle-cannabis-web v4.91 with indigo theme + "since 2010" heritage angle.
// 3.166 — Public /vendor-access self-serve form for brand partners (PLAN_VENDOR_ASSETS_PORTAL path B). Lands at /vendor-access — collects company + contact + email + phone + brand confirmation + intent — POSTs JSON to inventoryapp /api/vendor-access — feeds existing /admin/vendor-access-requests admin queue. Indexed (canonical), thanks page noindex. Free-text only — no file upload. Mirror page on seattle-cannabis-web v4.86.
// 3.161 — /brands/[slug] generic-template renders vendor-authored brand bio + Instagram/X/Facebook handles when filled in via /vmi/profile (inventoryapp). Section sits above the order CTA, only renders when at least one field is non-null. Handles are sanitized to /^[A-Za-z0-9._-]+$/ before being concatenated into URLs (prevents query-param injection or path traversal). Per-brand override components (NWCS, Mfused, Avitas etc.) intentionally NOT touched — those are graduated, hand-authored layouts.
// 3.156 — /apply personality prompts: two optional written prompts (product-recommendation pitch + customer-recovery story) capture personality signal without the photo discrimination risk. Stored in applicants.metadata JSONB on inventoryapp side. Compliance: written-only — no photo (WA RCW 49.60 / EEOC pre-offer photo discrimination risk).
// 3.151 — Public /apply form: apply-to-work intake with resume upload + 3 references + 21+ confirmation. POSTs to inventoryapp /api/applications. Compliance: no photo / no SSN / no DOB.
export const BUILD_VERSION = "3.260";

export const BUILD_SHA = (
  process.env.VERCEL_GIT_COMMIT_SHA ??
  process.env.NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA ??
  "dev"
).slice(0, 7);
