// Build identity exposed in the footer so Doug can verify a deploy landed.
// Bump BUILD_VERSION manually for major UX/feature changes; the short SHA
// comes from Vercel automatically on every deploy and is the authoritative
// "did my push actually land" signal.

// 3.360 — 3 more unused-var/import cleanups: `bondi-farms.tsx` (unused `Image`) + `avitas.tsx` (unused `BRAND_AMBER_LIGHT` const) + `PaginatedProductsGrid.tsx` (dropped 17-line dead `buckets` useMemo — category-grouping computation that nothing rendered). tsc clean.
// 3.355 — 2 unused-import lint cleanups: `app/account/profile/page.tsx` (unused `STORE`) + `app/brands/[slug]/_brands/2k-gardens.tsx` (unused `Link`). Both leftover from prior refactors. tsc clean.
// 3.350 — `app/alumni/page.tsx` — `<a href="/">` → `<Link>` for the customer-facing "Back to the shop" CTA. Real perf fix: `<a>` does a full page reload while `<Link>` does client-side nav (preserves cart state, reuses cached data, faster). Caught by `@next/next/no-html-link-for-pages` lint. tsc clean.
// 3.345 — `components/CartResumeBanner.tsx` — add 2 missing `eslint-disable-next-line react-hooks/rules-of-hooks` directives on `useEffect` calls. Component has `if (!PUBLIC_ORDER_ROUTE_LIVE) return null` early-return at line 69; the constant is hardcoded `false` so hooks below never execute. Author already disabled `usePathname`/`useSyncExternalStore`/`useState` calls but missed the 2 `useEffect`. Lint silence; runtime unchanged. tsc clean.
// 3.340 — `components/LoyaltyArc.tsx` JSX apostrophe fix (`We're` → `We&rsquo;re`). Caught by `pnpm lint` `react/no-unescaped-entities` on the customer-visible homepage loyalty section. Tiny 1-character JSX hygiene fix; renders identically but stops the lint error so future real-bug warnings don't get drowned in noise. Sister fix on seattle-cannabis-web v4.240. Skipped the 3 opengraph-image.tsx files since those are satori-rendered (HTML entities don't auto-decode). tsc clean.
// 3.335 — `lib/order-confirmation-email.ts` + `lib/welcome-email.ts` opt-out mailto switched from hardcoded `info@greenlifecannabis.com` to `RESEND_REPLY_TO ?? STORE.email`. Pre-fix the customer-facing footer line ("To stop future marketing emails, reply STOP or email info@greenlifecannabis.com") sent unsubscribers to an unmonitored inbox per `project_info_email_unmonitored` memory — same class of bug as inventoryapp v56.245 `/api/applications` reply-to. Post-fix: prefers `RESEND_REPLY_TO` env (set to monitored `buyer@greenlifecannabis.com` v3.325), falls through to STORE.email as last resort. Same env var that drives the Resend reply-to header so monitoring fate is now consistent across header + in-body opt-out paths. 2 files / 6 lines changed (3 hardcoded refs per file: HTML mailto + plain-text body + comment block documenting the WHY). tsc clean. Customer-facing fix — applicants/customers replying to opt out actually reach a monitored inbox now.
// 3.330 — `lib/sms.ts` upgraded to inventoryapp's `normalizeToE164` boundary pattern (companion to inventoryapp v50.345). Pre-fix: `sendSms()` passed raw `to` straight to Twilio without normalization; the existing `normalizePhone` helper was simplistic (only handled `+`-prefix and naive 10-digit, broke on formatted `(509) 555-0100` and 11-digit `1XXX...`). Post-fix: new `normalizeToE164(input)` handles raw 10-digit US, formatted US, already-E.164, 11-digit `1XXX`, 11+-digit international, and empty/short input (returns unchanged so Twilio rejection is the cleaner failure path). `sendSms()` now calls it at the boundary so callers don't have to remember. `normalizePhone` kept as a back-compat alias (E.164 round-trips unchanged, so existing inline calls in `/api/orders` keep working). Same surgery on seattle-cannabis-web v4.230. Single-file +35 LOC. tsc clean. Closes the SMS-helper drift between the inventoryapp + the two public sites flagged by `feedback_sms_e164_normalize_at_boundary`.
// 3.325 — `lib/email.ts` honors `RESEND_REPLY_TO` env var (default reply-to override). Pre-fix: customer replies to outbound mail defaulted to the From address — fine when From is monitored, but Wenatchee's `info@greenlifecannabis.com` From is NOT actively monitored (per memory `project_info_email_unmonitored`), so replies vanished. Post-fix: when `RESEND_REPLY_TO` env var is set, sendEmail() routes replies there instead. Per-call `replyTo` arg still wins; env-var default is the fallback. Wired live: `buyer@greenlifecannabis.com` set on this project (all 3 envs) since that mailbox IS actively monitored. Seattle unchanged — its From (`rainier@seattlecannabis.co`) is monitored so RESEND_REPLY_TO stays unset, but the helper now supports the env var symmetrically across both repos. Mirror on seattle-cannabis-web v4.225 (helper-only; no env var set).
// 3.320 — `/menu` server-side Dutchie prewarm. New `prewarmDutchieMenu()` async helper inside `app/menu/page.tsx` does a fire-alongside `fetch("https://api.iheartjane.com/api/v1/stores/5294/menu_products?per_page=1")` at SSR time, BEFORE the HTML response reaches the browser. Boost (which runs `afterInteractive` in `JaneMenu.tsx`) then queries the same URL ~200ms after page paint and hits Jane's now-warm edge cache — Dutchie cold-start time is amortized away from the customer's first paint. AbortSignal 1.5s timeout caps TTFB impact when Jane is unreachable; failure path silently swallowed (helper returns void). Closes the customer-reported "menu error coming up first pass" pattern (MenuFallback's amber 6s watchdog was firing on cold-Dutchie loads even though Boost was just-about to succeed). See MENU_LOG.md + MenuFallback.tsx FALLBACK_AFTER_MS for the dodged threshold. Mirror on seattle-cannabis-web v4.220.
// 3.315 — `/api/health` exposes `emailConfigured: boolean` for one-curl Resend wire-up verification. After adding `RESEND_API_KEY` env var to a Vercel project, this flag flips `true` on the next deploy. Boolean only — never the key value. Companion to seattle-cannabis-web v4.215 (same single-line addition, mirrors the email helper at `lib/email.ts`).
// 3.311 — vendor-ads `daily_impression_cap` render-side enforcement (companion to inventoryapp v49.705 + migration 0158). `getActiveVendorAds()` now (1) excludes any ad whose TODAY's count has already hit cap via WHERE branch — `last_impression_day IS DISTINCT FROM today OR impressions_today < cap`, (2) atomic post-SELECT UPDATE increments `impressions_today` (or resets to 1 if day rolled over). Day boundary computed in `America/Los_Angeles` so rollover lines up with Kat's calendar. Lazy-reset semantics — no daily cron required. UPDATE failure swallowed (render quality > telemetry). Mirror on seattle-cannabis-web v4.211.
// 3.305 — `/api/health` redacts Neon endpoint ID from `db.host`. Pre-fix exposed `ep-divine-voice-ant9tbpu-pooler.c-6.us-east-1.aws.neon.tech` to anonymous health-check callers — the leading label uniquely identifies the Neon project. Now redacts to `***.c-6.us-east-1.aws.neon.tech` — keeps cluster/region/provider for ops "is this Neon? right region?" debug, drops project-uniqueness leak. Same fix on seattle-cannabis-web v4.200 + inventoryapp v49.045. Auth'd ops reading raw env var still see full hostname.
// 3.300 — Stale `/brands` index reference cleaned up in dev landing page (`app/dev/page.tsx`). Row was pointing at the deleted index (308's to /menu via v3.290 middleware) with a misleading "Per-vendor product listings" blurb. Repurposed to point at a sample boutique override page (`/brands/nwcs`) so Doug + devs previewing the dev menu can see the live `/brands/[slug]` template. Greenlife-only — Seattle has no `/dev` route. Single-file ship, single-line + comment block.
// 3.295 — VendorAdSlot wired to 4 remaining placement slots: homepage_top (above hero), homepage_under_brands (below brands carousel), menu_sidebar (above iHeartJane Boost embed on /menu), brand_page_top (top of /brands/[slug] generic template). All slots silent until admin curates active ads at inventoryapp /admin/marketing/vendor-ads. Now 5 of 5 schema-enum slots are mounted. Mirror on seattle-cannabis-web v4.195.
// 3.290 — `/brands` redirect FINAL FIX in `proxy.ts` middleware. v3.265's page-level approach (`permanentRedirect()` + `dynamic = "force-dynamic"`) deployed but did NOT produce a real HTTP 308 — Next 16 served HTTP 200 with homepage HTML body even though page was rendered dynamically (no `x-vercel-cache: HIT`). Middleware-level intercept runs BEFORE Next's render pipeline; response is a guaranteed real HTTP 308 with `location: /menu`. Page-level fallback in `app/brands/page.tsx` remains as defense-in-depth. Closes the `🟡 /brands redirect caveat` flag in LIVE.md. Mirror on seattle-cannabis-web v4.190.
// 3.281 — `proxy.ts` `ALWAYS_CANONICAL_HOSTS` belt-and-suspenders set added (parity with seattle-cannabis-web). Defends against `NEXT_PUBLIC_CANONICAL_HOST` env-var misconfiguration — if anyone ever sets it to a stale value or per-deployment Vercel URL, `isCanonicalOrLocal()` still treats `www.greenlifecannabis.com` as canonical and won't redirect customers AWAY from it. Same defense class as the inventoryapp cross-store warp hardening (v45.205) — env-var misconfig shouldn't be able to break SSO/CORS pinning. Mirror of Seattle's existing pattern. Single-line addition + comment block. Single-file. tsc clean.
// 3.270 — `/brands` redirect moved to proxy.ts middleware (FIRST attempt — see v3.290 for the actual ship). Note: this entry never landed in production with the middleware change because the proxy.ts edit didn't get committed in the same push. Kept here as historical narrative.
// 3.265 — `/brands` redirect SEO fix. Was returning HTTP 200 + a Next.js Loading-then-`router.push("/menu")` static payload (Next 16 captures `redirect()` during prerender as static HTML when there's no `dynamic = "force-dynamic"` directive on the page). Crawlers + uptime checks + curl saw 200 + empty body, not a redirect. Now: `export const dynamic = "force-dynamic"` forces per-request render, and `redirect` swapped for `permanentRedirect` so the response is a real HTTP 308 → /menu (matches the page comment's stated intent + the LIVE.md follow-up note). SEO impact: search engines + crawlers + monitors now see a proper permanent redirect; link equity from any inbound `/brands` references flows correctly to /menu. Mirror on seattle-cannabis-web v4.175.
// 3.260 — Homepage 🆕 Just In section. New `getJustInProducts(12)` lib fn pulls products with `inventory_snapshots.first_seen ≤ 7 days ago`, in stock now, with image, brand-with-recent-sales gate (same anti-leak as getMenuProducts). Renders above the (still-disabled-pending-/order-ship) Today's Picks block as a fresh 4-column grid with a "🆕 New" pill in the corner of each card. CTA links to /menu (iHeartJane Boost) — distinct from the in-dev /order tree. Distinct from curated /admin/marketing/featured (curated = hot picks, this = what's new). Doug 2026-05-04 "featured new products" — curated answers "featured", this answers "new". Mirror on seattle-cannabis-web v4.170.
// 3.255 — `getFeaturedProducts()` reads curated mode first. When admin (Kat/Doug) flips ON `is_featured` for any active product at inventoryapp /admin/marketing/featured (migration 0154), those products win the homepage carousel — sorted by `featured_priority DESC NULLS LAST, name ASC`. Falls back to the existing recent-`updated_at`-on-brands-with-sales auto-mode when zero curated. Companion to inventoryapp v44.x ship that landed migration 0154 + the admin curation surface. Mirror on seattle-cannabis-web v4.165.
// 3.250 — Homepage closure-aware. Adds `fetchClosureStatus()` to the page-level `Promise.all` and threads `closure.isClosed` into the existing `const open = isOpenNow()` so all 3 hero/strip/pre-footer "Open Now / Closed" indicators flip to "Closed" when a manager has flipped the emergency-closure override — matching the reality of the store, not just configured weekly hours. Also renders `<ClosureBanner>` at the very top of the page (above the hero) inside an amber strip for explicit reason context. Closure-aware customer surfaces now: `/` (v3.250) + `/menu` (v3.240) + `/order` (v3.230) + `/visit` (v3.245). Mirror on seattle-cannabis-web v4.160.
// 3.245 — `/visit` closure banner. Extends v3.240 to the third high-traffic customer entry point: the visit-info page (hours + directions + parking) where pre-drive customers land. Server Component made async to call `fetchClosureStatus()` server-side; banner renders above the hero when closed (consistent with /menu placement). Page already has `revalidate = 300` 5-min ISR so the closure-status fetch happens at most once per 5min per region. Closure-aware customer surfaces now: /menu (v3.240) + /order (v3.230) + /visit (v3.245). Mirror on seattle-cannabis-web v4.155.
// 3.240 — `/menu` server-rendered closure banner. Extends v3.230's `/order` banner to the higher-traffic `/menu` (iHeartJane Boost embed) entry point. New `<ClosureBanner>` component (presentational, used by both `/menu` server-side + `/order` client-side via prop). `/menu` page.tsx now does `Promise.all([getActiveDeals, fetchClosureStatus])` server-side; banner renders above the heading + JaneMenu when closed. ISR 60s on the page bounds the fetch frequency. Same graceful-degrade behavior — endpoint unreachable = banner doesn't render. Mirror on seattle-cannabis-web v4.150.
// 3.235 — `/brands` index deletion code lands (v3.225 changelog described this; that entry shipped via the closure-banner agent's bundle but the code edits were still uncommitted in working tree). This commit lands the actual file deletions + nav-strip + breadcrumb edits.
// 3.230 — `/order` block-on-closure banner. Fetches inventoryapp `/api/public/closure-status` on mount + before-submit re-check inside `placeOrder()`. When manager has flagged today closed via `/admin/hours-override`, surfaces an amber banner with the reason text, disables the Place Order button (label flips to "Closed today"), and the before-submit guard prevents a stale-state race. New `lib/closure-status.ts` helper wraps the fetch with a 5s AbortController timeout + always returns `{isClosed:false}` on any error path so a flaky endpoint never silently blocks ordering during normal hours. Default endpoint base = `inventoryapp-ivory.vercel.app`, overridable via `NEXT_PUBLIC_INVENTORYAPP_URL` (https-only). Closes the visibility chain queued in claude-loop-grinder Batch A items 1+2 (admin override v9.395 → public endpoint v9.745 → public-site banner now). Mirror on seattle-cannabis-web v4.140.
// 3.225 — `/brands` index page deleted (Doug + Kat call 2026-05-04). Even after the v3.181/v3.187/v3.205/v3.211 filter chain locked the data down to "products we currently carry + sold within 365 days," Kat's reasons for deletion were structural, not data-quality: (a) the page exposed our full vendor relationship list to outsiders; (b) it made daily-deal vendor concentration glanceable. Boutique `/brands/[slug]` overrides KEPT — they pull SEO traffic for "Phat Panda Wenatchee" / "Avitas WA" etc. queries and pay for themselves on direct link-sharing + deal-card click-throughs. **Touched:** index → 308 redirect to `/menu` (preserves any inbound link equity); SiteHeader nav, SiteFooter, home `Top Brands` section header (kept the section but stripped the "All N brands" + "+more" + empty-state links to the deleted index), about + visit page mesh tiles, not-found suggestion list, sitemap, llms.txt + llms-full.txt, vendor-access thanks page, blog post body. **`/brands/[slug]` template:** dropped "← All Brands" footer backlink + dropped "All Brands /" top-of-hero breadcrumb + dropped the "Brands" rung from the BreadcrumbList JSON-LD (now Home → {brand}). Per-brand override components (NWCS, Mfused, Avitas, Phat Panda, Plaid Jacket, etc.) intentionally NOT touched — those are graduated hand-authored layouts. Mirror on seattle-cannabis-web v4.135.
// 3.211 — Brand-leakage round 3 — sales-history gate extended to product surfaces (/order, /shop, /stash, home featured carousel, home category previews, brand-products grid). Round 2 (v3.205) only gated brand pages; products from leaked brands could still appear on /menu+/order+/shop because those don't go through getActiveBrands/getBrandBySlug. Now `getMenuProducts` + `getProductsByIds` + `getFeaturedProducts` (+ fallback) + `getCategoryPreviewProducts` + `getBrandProducts` all INNER JOIN `brands_with_recent_sales` (vendors with ≥1 sale_line_items.sold_at >= NOW() - INTERVAL '365 days'). Customer-facing product display surfaces are now uniformly gated. Mirror on seattle-cannabis-web v4.125.
// 3.205 — Brand-leakage round 2 — sales-history gate added to brand queries (Doug screenshot 2026-05-04: "ABS Buds" Wenatchee-era brand showing on Seattle with 13 FOG concentrate SKUs). Root cause: Seattle Neon has leaked inventory_snapshots from a seed migration; v4.107 qty>0 guard couldn't distinguish "real Seattle inventory" from "ghost inventory from a Wenatchee-seeded product." `getActiveBrands` + `getBrandBySlug` now INNER JOIN a `brands_with_recent_sales` CTE — each Neon DB only has THAT store's sales (per CLAUDE.md), so a `sale_line_items.sold_at >= NOW() - INTERVAL '365 days'` row = customer paid for it at this register. Brands without any tail sale at this store get hidden from /brands index AND 404 on direct `/brands/[slug]` visits (so the hand-authored override components for Wenatchee-only brands don't render either). Same fix on seattle-cannabis-web v4.119.
// 3.199 — `proxy.ts` /api/health exemption broadened from exact-equality to `startsWith("/api/health")` so the cheap second-bucket /api/health/ping liveness endpoint also stays reachable on apex / per-deployment Vercel URLs. Pre-fix: v3.193 fixed /api/health on apex but /api/health/ping was still 308'ing (uptime monitors that hit /ping every 30-60s for second-bucket liveness can't follow that redirect cleanly). Same fix applied to seattle-cannabis-web — covers both endpoints across both stores.
// 3.193 — `proxy.ts` /api/health exemption from the canonical-host 308 (parity with seattle-cannabis-web). Pre-fix: hitting `https://greenlifecannabis.com/api/health` (apex) or any per-deployment Vercel URL returned 308 → www, masking host-specific liveness signal — external uptime monitors, post-deploy LKG verification curls, and per-PR-deploy smoke-tests all got redirected away from the host they were probing. Now `if (!isCanonicalOrLocal && pathname !== "/api/health")` mirrors Seattle's behavior. Single line + comment update. No customer impact (customers don't hit /api/health). Curl from apex now returns 200 directly.
// 3.187 — Brand pages + featured + category previews now require current inventory (Doug bug report 2026-05-04 "showing items we hant had in a long time on both stores"). Layers on top of v3.181/v3.182 carry_status tightening: those went from `!=discontinued` to `=active` but didn't add a stock-level guard. Now `getActiveBrands` + `getBrandBySlug` + `getBrandProducts` + `getFeaturedProducts` (+ its 4-row fallback) + `getCategoryPreviewProducts` all join the canonical `latest_inv` CTE (`SELECT DISTINCT ON (product_id) ... ORDER BY product_id, captured_at DESC`) and filter `li.qty > 0`. Same pattern already in `getMenuProducts` + `getProductsByIds`. Customer no longer sees brands that haven't shipped a SKU in months, or "featured" products with empty shelves. WSLCB advertising-accuracy + customer-trust fix. Mirror on seattle-cannabis-web v4.107.
// 3.182 — `/order` + `/shop` + `/stash` product filter tightened (Doug bug report 2026-05-04 "saying we have things that we dont"). `getMenuProducts` + `getProductsByIds` in `lib/db.ts` now require strict `carry_status = 'active'` (was `!= 'discontinued'`, which included `phasing_out`) AND INNER JOIN to a latest-snapshot `qty > 0` CTE (was no current-stock filter at all — only the historical 7-day `is_new` subquery had any qty filter). Pairs with v3.181 brand-page tightening: same root cause (loose filter set), different consuming surfaces. Mirrors the inventoryapp `lib/menu-server.ts` canonical pattern. WSLCB advertising-accuracy + customer-trust fix. Mirror on seattle-cannabis-web v4.102.
// 3.181 — `/brands/[slug]` + `/brands` tightened product filter (Kat bug report 2026-05-04). `getActiveBrands` + `getBrandBySlug` + `getBrandProducts` in `lib/db.ts` now require `carry_status = 'active' AND unit_price > 0` instead of the looser `carry_status != 'discontinued'`. Hides phasing-out vendors, $0-priced placeholder rows, and Wenatchee-era stale products that customers were finding on brand pages we don't actually carry (Bon Bombs since-Wes era surfaced this). Same change shipped to seattle-cannabis-web v4.101 — Seattle had it worse since their DB inherited Wenatchee-era seed brands. SQL stays one query each, no N+1 introduced.
// 3.176 — Apply form `?position=` deep-link support — when /careers links to /apply?position={id}, form fetches position from inventoryapp API, pre-selects role + shows 'Applying for: {title}' pill at top. Hidden positionId field passes the link to /api/applications. Silent fallback when fetch fails or position no longer open.
// 3.171 — Public /careers landing (Hiring Phase 5). Fetches open positions from inventoryapp /api/positions/open?store=wenatchee with 5-min ISR + 5s fetch timeout (falls back to "we keep good resumes on file" empty state on any failure). Position cards: title, store badges (handles either→both), pay-range/hours-pattern chips, safe-markdown description (paragraphs + bullets + **bold** only — no HTML pass-through, XSS-safe), "Apply for this role" CTA deep-linking /apply?position={id}. Hero leans on Wenatchee's "best staff" angle (no "locally-owned" framing per project_wenatchee_positioning_best_staff). Mirror on seattle-cannabis-web v4.91 with indigo theme + "since 2010" heritage angle.
// 3.166 — Public /vendor-access self-serve form for brand partners (PLAN_VENDOR_ASSETS_PORTAL path B). Lands at /vendor-access — collects company + contact + email + phone + brand confirmation + intent — POSTs JSON to inventoryapp /api/vendor-access — feeds existing /admin/vendor-access-requests admin queue. Indexed (canonical), thanks page noindex. Free-text only — no file upload. Mirror page on seattle-cannabis-web v4.86.
// 3.161 — /brands/[slug] generic-template renders vendor-authored brand bio + Instagram/X/Facebook handles when filled in via /vmi/profile (inventoryapp). Section sits above the order CTA, only renders when at least one field is non-null. Handles are sanitized to /^[A-Za-z0-9._-]+$/ before being concatenated into URLs (prevents query-param injection or path traversal). Per-brand override components (NWCS, Mfused, Avitas etc.) intentionally NOT touched — those are graduated, hand-authored layouts.
// 3.156 — /apply personality prompts: two optional written prompts (product-recommendation pitch + customer-recovery story) capture personality signal without the photo discrimination risk. Stored in applicants.metadata JSONB on inventoryapp side. Compliance: written-only — no photo (WA RCW 49.60 / EEOC pre-offer photo discrimination risk).
// 3.151 — Public /apply form: apply-to-work intake with resume upload + 3 references + 21+ confirmation. POSTs to inventoryapp /api/applications. Compliance: no photo / no SSN / no DOB.
export const BUILD_VERSION = "3.360";

export const BUILD_SHA = (
  process.env.VERCEL_GIT_COMMIT_SHA ??
  process.env.NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA ??
  "dev"
).slice(0, 7);
